name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Node Setup & Yarn Install
        uses: ./.github/actions/setup

      - name: Check for no duplicate dependencies
        run: yarn dedupe --check

      - name: Verify Sanity schema
        run: yarn sanity schema validate

      - name: Generate Sanity types
        run: yarn sanity:gen

      - name: Generate GraphQL
        run: yarn gql:gen

      - name: Check TypeScript
        run: yarn type-check

      - name: Lint
        run: yarn eslint --max-warnings 0 .
        continue-on-error: true

      - name: Build
        run: yarn build
